wip: DE-756
arangodb/python-arango pull request #323
Opened 2024-02-02 22:02 UTC by aMahanna

todo: Figure out why CI is failing

2024-03-08 15:02 UTC, aMahanna commented on tests/test_view.py
> +        assert "optimizeTopK" in res
this is failing

2024-04-26 14:13 UTC, aMahanna commented on tests/test_view.py
> +        assert "optimizeTopK" in res
example CI failure: https://app.circleci.com/pipelines/github/arangodb/python-arango/350/workflows/5c928ec3-5bb4-4371-be55-266fedb562d7/jobs/8415

2024-04-26 15:38 UTC, alexbakharew requested changes
Hi! `optimizeTopK` was introduced only for 3.12. That is why it is failing for 3.11

2024-04-26 15:58 UTC, aMahanna commented
@alexbakharew thank you! resolved

2024-04-26 15:59 UTC, apetenchea approved these changes
LGTM

2024-04-26 16:03 UTC, merged